### ISSUE TITLE
Why is the cast specification so short?

### ISSUE THREAD

**Issue by LDataCraft** [MarioGehrke/Film#1]
Dear Mario, I was wondering why your casting specification is so incredibly short?

Would love to get some Feedback form you.

Thanks!

**Comment by ghost** [comment]
just because

**Comment by MarioGehrke** [comment]
weil das script nicht mehr braucht

**Comment by ghost** [comment]
i think i spider

**Comment by AlfonsoGazzo** [comment]
hello

**Comment by nora-monajjed** [comment]
😊

**Comment by ghost** [comment]
My lovely mister singing club... Heaven thunder weather my farseeing picture umbrella is in the bucket
